from ic_agent.config import (
    GOOGLE_DRIVE_FOLDER_ID,
    GOOGLE_OPPM_FOLDER_ID,
    GOOGLE_SRS_FOLDER_ID,
    GOOGLE_REPORTS_FOLDER_ID,
)

print('GOOGLE_DRIVE_FOLDER_ID=', GOOGLE_DRIVE_FOLDER_ID)
print('GOOGLE_OPPM_FOLDER_ID=', GOOGLE_OPPM_FOLDER_ID)
print('GOOGLE_SRS_FOLDER_ID=', GOOGLE_SRS_FOLDER_ID)
print('GOOGLE_REPORTS_FOLDER_ID=', GOOGLE_REPORTS_FOLDER_ID)
